apiVersion: k8s.io/v1
kind: Ingress
metadata:
 name: go-ingress
 namespace: golang
spec:
 rules:
 - host: golang.ekanadh.xyz
   http:
     paths:
     - path:
       backend:
         serviceName:  go-svc
         servicePort: 80
