#apiVersion: v1
#kind: Service
#metadata:
 # name: go-svc
  #namespace: golang
#spec:
 # selector:
  #  app: golang-app
  #ports:
  #- port: 80
   # targetPort: 8081
    
    
apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector:
    app: example
  ports:
    - port: 80
      targetPort: 8081
  type: LoadBalancer
